/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParticlepegRouteImport } from './routes/particlepeg'
import { Route as LostInSpaceRouteImport } from './routes/lost-in-space'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ParticlepegRoute = ParticlepegRouteImport.update({
  id: '/particlepeg',
  path: '/particlepeg',
  getParentRoute: () => rootRouteImport,
} as any)
const LostInSpaceRoute = LostInSpaceRouteImport.update({
  id: '/lost-in-space',
  path: '/lost-in-space',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lost-in-space': typeof LostInSpaceRoute
  '/particlepeg': typeof ParticlepegRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lost-in-space': typeof LostInSpaceRoute
  '/particlepeg': typeof ParticlepegRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lost-in-space': typeof LostInSpaceRoute
  '/particlepeg': typeof ParticlepegRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/lost-in-space' | '/particlepeg'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/lost-in-space' | '/particlepeg'
  id: '__root__' | '/' | '/about' | '/lost-in-space' | '/particlepeg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LostInSpaceRoute: typeof LostInSpaceRoute
  ParticlepegRoute: typeof ParticlepegRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/particlepeg': {
      id: '/particlepeg'
      path: '/particlepeg'
      fullPath: '/particlepeg'
      preLoaderRoute: typeof ParticlepegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-in-space': {
      id: '/lost-in-space'
      path: '/lost-in-space'
      fullPath: '/lost-in-space'
      preLoaderRoute: typeof LostInSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LostInSpaceRoute: LostInSpaceRoute,
  ParticlepegRoute: ParticlepegRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
